### ISSUE TITLE
The given key 'HandheldCompanion.Views.QuickPages.QuickProfilesPage' was not present in the dictionary. 

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#1019]
Note this on an unsupported device the OneXPlayer X1 (Core Ultra 155H)

**Handheld Companion Version**
0.20.5.4

**Describe the bug**

**To Reproduce**
Start the app, results in crash.

**Logs file**
```
2024-04-01 10:28:27.757 +02:00 [FTL] The given key 'HandheldCompanion.Views.QuickPages.QuickProfilesPage' was not present in the dictionary.	   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

   at HandheldCompanion.Misc.PowerProfile.Check(Page page) in C:\Users\ROGAlly\Projects\HandheldCompanionRepo\HandheldCompanion-EA\HandheldCompanion\Misc\PowerProfile.cs:line 252

   at HandheldCompanion.Views.QuickPages.QuickProfilesPage.<>c__DisplayClass22_0.<ProfileManager_Applied>b__0() in C:\Users\ROGAlly\Projects\HandheldCompanionRepo\HandheldCompanion-EA\HandheldCompanion\Views\QuickPages\QuickProfilesPage.xaml.cs:line 458

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location ---

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at HandheldCompanion.App.Main()
```

[HandheldCompanion-20240401.log](https://github.com/Valkirie/HandheldCompanion/files/14850685/HandheldCompanion-20240401.log)

**Comment by Valkirie** [comment]
Fixed with https://github.com/Valkirie/HandheldCompanion-EA/commit/b204ab6f4ac1971d5b147d5591aa91f98bd79a05
