### ISSUE TITLE
TDP and GPU cannot be set

### ISSUE THREAD

**Issue by PJnoeru** [Valkirie/HandheldCompanion#1039]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [x] GPD
- [ ] LENOVO
- [ ] MSI
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
GPD WIN MAX2 (6800U)

**Handheld Companion Version**
0.21.0.1

**Describe the bug**
TDP and GPU frequency cannot be set, and the setting options are grayed out.
After uninstalling, the installation will take place, but the problem persists.

**To Reproduce**
When playing a game, after the TPD is set to full load, when exiting the game, a crash or disconnection occurs, and the power is manually forced to shut down, and the TDP and GPU frequency cannot be set after powering on.

I don't know how to recover from this situation, and the tpd option is always grayed out, even with administrator privileges.
However, other TDP tools work fine.

**Expected behavior**
How should I recover the tdp and gpu frequency settings from this case？

【Translation support using Microsoft Translator】

**Screenshots**
![PixPin_2024-04-20_09-40-51](https://github.com/Valkirie/HandheldCompanion/assets/41642563/7f58f698-bd36-4d13-b299-a4378fb86f42)
![image](https://github.com/Valkirie/HandheldCompanion/assets/41642563/70a75a22-c6fb-4ea6-984b-f12d88395588)

**Comment by PJnoeru** [comment]
How should I recover the tdp and gpu frequency settings from this case？

**Comment by CasperH2O** [comment]
Sorry to hear you are having trouble.

@PJnoeru can you share a logfile from c:programfiles/handheld companion/logs ?

**Comment by PJnoeru** [comment]
[HandheldCompanion-20240420_002.log](https://github.com/Valkirie/HandheldCompanion/files/15046860/HandheldCompanion-20240420_002.log)
Because I uninstalled and reinstalled, the previous log seems to be lost.

**Comment by CasperH2O** [comment]
Seeing this error crash in the log: 

`2024-04-20 02:17:58.771 +08:00 [FTL] Object reference not set to an instance of an object.	   at HandheldCompanion.Managers.PerformanceManager.Stop() in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\Managers\PerformanceManager.cs:line 891
   at HandheldCompanion.Views.MainWindow.Window_Closed(Object sender, EventArgs e) in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\Views\Windows\MainWindow.xaml.cs:line 682
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)`

I see you are also running Motion Assistant and HC at the same time, they might conflict.

**Comment by CasperH2O** [comment]
I can't tell from the log why TDP or GPU control would not work for you. You can try installing again, but if that doesn't work I have no further ideas.

**Comment by PJnoeru** [comment]
The Motion Assistant is only used to test if there is a BIOS problem that causes TDP to be unable to set the settings to verify the use

**Comment by Valkirie** [comment]
The app "Failed to retrieve processor family:". Can you head into MyDocuments,HC,cache and remove the motherboardinfo file then restart HC ?

**Comment by PJnoeru** [comment]
In addition, after I uninstalled HC and restarted, the following form popped up, but the window disappeared after clicking on the option, and there was no other response
![PixPin_2024-04-20_13-17-30](https://github.com/Valkirie/HandheldCompanion/assets/41642563/e28c3364-cf2c-443f-b993-ed23a06cf715)

Also, after installing HC, the RTSS error window pops up,I can only install (MSIAfterburnerSetup466Beta3) again for an overwrite install of rtss for the error window to go away.
![PixPin_2024-04-20_13-23-09](https://github.com/Valkirie/HandheldCompanion/assets/41642563/9130401e-b458-463b-b2b8-d725f5c33e7d)

Finally, uninstall Motion Assistant and reinstall HC, the result is still not set, how should I completely remove all the residues when the software is uninstalled?including the configuration files, so as to install more thoroughly and cleanly, after uninstalling HC, there are a large number of residual files in the installation path, even if you delete them, it still doesn't work.

**Comment by Valkirie** [comment]
> In addition, after I uninstalled HC and restarted, the following form popped up, but the window disappeared after clicking on the option, and there was no other response ![PixPin_2024-04-20_13-17-30](https://private-user-images.githubusercontent.com/41642563/324156459-e28c3364-cf2c-443f-b993-ed23a06cf715.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTE3MDUsIm5iZiI6MTcxMzU5MTQwNSwicGF0aCI6Ii80MTY0MjU2My8zMjQxNTY0NTktZTI4YzMzNjQtY2YyYy00NDNmLWI5OTMtZWQyM2EwNmNmNzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA1MzY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5YzQwMzI1ZWRjMTVkNzExZjVmOWE2NzdhNDIzMDliN2Y1YTZjN2ExYTA1ZGMyZTcxMWFmMTQwZmQ3NTcwNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RN3mOHeOeo_2TJOUHk9S_54eo6OoBtSNkDx_IY-tTyE)
> 
> Also, after installing HC, the RTSS error window pops up,I can only install (MSIAfterburnerSetup466Beta3) again for an overwrite install of rtss for the error window to go away. ![PixPin_2024-04-20_13-23-09](https://private-user-images.githubusercontent.com/41642563/324156537-9130401e-b458-463b-b2b8-d725f5c33e7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTE3MDUsIm5iZiI6MTcxMzU5MTQwNSwicGF0aCI6Ii80MTY0MjU2My8zMjQxNTY1MzctOTEzMDQwMWUtYjQ1OC00NjNiLWIyYjgtZDcyNWY1YzMzZTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA1MzY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZmMzNmQyZWI1ODg4ZmFlMTg5M2UxN2UwMTRkZmM2ZThjNmZiNGU5NmQ3OTFiN2ZiYmM1ZjVhODU0ZDUzYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._EPj5_6qlG1tuohKLEM1yd0fRaMsysGAxyxh7POQyTE)
> 
> Finally, uninstall Motion Assistant and reinstall HC, the result is still not set, how should I completely remove all the residues when the software is uninstalled?including the configuration files, so as to install more thoroughly and cleanly, after uninstalling HC, there are a large number of residual files in the installation path, even if you delete them, it still doesn't work.

Hey, see my above post. We'd like to give a look at your motherboard.json file. Then delete it and restart HC.

**Comment by PJnoeru** [comment]
> > 另外，卸载HC重启后，弹出了以下表单，但点击选项后窗口消失了，没有其他响应![PixPin_2024-04-20_13-17-30](https://private-user-images.githubusercontent.com/41642563/324156459-e28c3364-cf2c-443f-b993-ed23a06cf715.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTE3MDUsIm5iZiI6MTcxMzU5MTQwNSwicGF0aCI6Ii80MTY0MjU2My8zMjQxNTY0NTktZTI4YzMzNjQtY2YyYy00NDNmLWI5OTMtZWQyM2EwNmNmNzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA1MzY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5YzQwMzI1ZWRjMTVkNzExZjVmOWE2NzdhNDIzMDliN2Y1YTZjN2ExYTA1ZGMyZTcxMWFmMTQwZmQ3NTcwNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RN3mOHeOeo_2TJOUHk9S_54eo6OoBtSNkDx_IY-tTyE)
> > 另外，安装HC后，会弹出RTSS错误窗口，我只能再次安装（MSIAfterburnerSetup466Beta3）以覆盖rtss的安装，错误窗口才能消失。![PixPin_2024-04-20_13-23-09](https://private-user-images.githubusercontent.com/41642563/324156537-9130401e-b458-463b-b2b8-d725f5c33e7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTE3MDUsIm5iZiI6MTcxMzU5MTQwNSwicGF0aCI6Ii80MTY0MjU2My8zMjQxNTY1MzctOTEzMDQwMWUtYjQ1OC00NjNiLWIyYjgtZDcyNWY1YzMzZTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA1MzY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZmMzNmQyZWI1ODg4ZmFlMTg5M2UxN2UwMTRkZmM2ZThjNmZiNGU5NmQ3OTFiN2ZiYmM1ZjVhODU0ZDUzYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._EPj5_6qlG1tuohKLEM1yd0fRaMsysGAxyxh7POQyTE)
> > 最后，卸载运动助手并重新安装HC，结果仍然没有设置，卸载软件时该如何完全清除所有残留物，包括配置文件，以便安装得更彻底干净，卸载HC后，安装路径中有大量残留文件，即使你删除了它们， 它仍然不起作用。
> 
> 嘿，看我上面的帖子。我们想看看您的motherboard.json文件。然后删除它并重新启动 HC。

[motherboard.zip](https://github.com/Valkirie/HandheldCompanion/files/15046994/motherboard.zip)
This is the previous motherboard.json, deleted it and restarted the HC, the TDP settings did get restored, the issue with the rtss above may need to be fixed

Last issue, I'm not sure if I need to reinstall HC again, the handle is not available at the moment.
![image](https://github.com/Valkirie/HandheldCompanion/assets/41642563/8fa6a230-4785-4402-ad53-230a107be5ae)

**Comment by PJnoeru** [comment]
> > In addition, after I uninstalled HC and restarted, the following form popped up, but the window disappeared after clicking on the option, and there was no other response ![PixPin_2024-04-20_13-17-30](https://private-user-images.githubusercontent.com/41642563/324156459-e28c3364-cf2c-443f-b993-ed23a06cf715.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTE3MDUsIm5iZiI6MTcxMzU5MTQwNSwicGF0aCI6Ii80MTY0MjU2My8zMjQxNTY0NTktZTI4YzMzNjQtY2YyYy00NDNmLWI5OTMtZWQyM2EwNmNmNzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA1MzY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5YzQwMzI1ZWRjMTVkNzExZjVmOWE2NzdhNDIzMDliN2Y1YTZjN2ExYTA1ZGMyZTcxMWFmMTQwZmQ3NTcwNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RN3mOHeOeo_2TJOUHk9S_54eo6OoBtSNkDx_IY-tTyE)
> > Also, after installing HC, the RTSS error window pops up,I can only install (MSIAfterburnerSetup466Beta3) again for an overwrite install of rtss for the error window to go away. ![PixPin_2024-04-20_13-23-09](https://private-user-images.githubusercontent.com/41642563/324156537-9130401e-b458-463b-b2b8-d725f5c33e7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTE3MDUsIm5iZiI6MTcxMzU5MTQwNSwicGF0aCI6Ii80MTY0MjU2My8zMjQxNTY1MzctOTEzMDQwMWUtYjQ1OC00NjNiLWIyYjgtZDcyNWY1YzMzZTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA1MzY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZmMzNmQyZWI1ODg4ZmFlMTg5M2UxN2UwMTRkZmM2ZThjNmZiNGU5NmQ3OTFiN2ZiYmM1ZjVhODU0ZDUzYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._EPj5_6qlG1tuohKLEM1yd0fRaMsysGAxyxh7POQyTE)
> > Finally, uninstall Motion Assistant and reinstall HC, the result is still not set, how should I completely remove all the residues when the software is uninstalled?including the configuration files, so as to install more thoroughly and cleanly, after uninstalling HC, there are a large number of residual files in the installation path, even if you delete them, it still doesn't work.
> 
> Hey, see my above post. We'd like to give a look at your motherboard.json file. Then delete it and restart HC.



> > In addition, after I uninstalled HC and restarted, the following form popped up, but the window disappeared after clicking on the option, and there was no other response ![PixPin_2024-04-20_13-17-30](https://private-user-images.githubusercontent.com/41642563/324156459-e28c3364-cf2c-443f-b993-ed23a06cf715.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTE3MDUsIm5iZiI6MTcxMzU5MTQwNSwicGF0aCI6Ii80MTY0MjU2My8zMjQxNTY0NTktZTI4YzMzNjQtY2YyYy00NDNmLWI5OTMtZWQyM2EwNmNmNzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA1MzY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5YzQwMzI1ZWRjMTVkNzExZjVmOWE2NzdhNDIzMDliN2Y1YTZjN2ExYTA1ZGMyZTcxMWFmMTQwZmQ3NTcwNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RN3mOHeOeo_2TJOUHk9S_54eo6OoBtSNkDx_IY-tTyE)
> > Also, after installing HC, the RTSS error window pops up,I can only install (MSIAfterburnerSetup466Beta3) again for an overwrite install of rtss for the error window to go away. ![PixPin_2024-04-20_13-23-09](https://private-user-images.githubusercontent.com/41642563/324156537-9130401e-b458-463b-b2b8-d725f5c33e7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTE3MDUsIm5iZiI6MTcxMzU5MTQwNSwicGF0aCI6Ii80MTY0MjU2My8zMjQxNTY1MzctOTEzMDQwMWUtYjQ1OC00NjNiLWIyYjgtZDcyNWY1YzMzZTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA1MzY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZmMzNmQyZWI1ODg4ZmFlMTg5M2UxN2UwMTRkZmM2ZThjNmZiNGU5NmQ3OTFiN2ZiYmM1ZjVhODU0ZDUzYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._EPj5_6qlG1tuohKLEM1yd0fRaMsysGAxyxh7POQyTE)
> > Finally, uninstall Motion Assistant and reinstall HC, the result is still not set, how should I completely remove all the residues when the software is uninstalled?including the configuration files, so as to install more thoroughly and cleanly, after uninstalling HC, there are a large number of residual files in the installation path, even if you delete them, it still doesn't work.
> 
> Hey, see my above post. We'd like to give a look at your motherboard.json file. Then delete it and restart HC.

[motherboard.zip](https://github.com/Valkirie/HandheldCompanion/files/15046994/motherboard.zip)
This is the previous motherboard.json, deleted it and restarted the HC, the TDP settings did get restored, the issue with the rtss above may need to be fixed

There is one more problem, I'm not sure if I need to reinstall HC again, the handle is not available at the moment.
![image](https://github.com/Valkirie/HandheldCompanion/assets/41642563/8fa6a230-4785-4402-ad53-230a107be5ae)

**Comment by gpdwin4** [comment]
hi, also happened to my gpd win 4,exactly the same. happened after update, can't share logs because it's uninstalled and gone. but i will share json file from hc folder in document. thanks
[motherboard.json](https://github.com/Valkirie/HandheldCompanion/files/15130202/motherboard.json)

**Comment by iknow2333** [comment]
My steam deck also have this problem,but delete motherboard.json and restart HC work for me.

**Comment by gpdwin4** [comment]
> My steam deck also have this problem,but delete motherboard.json and restart HC work for me.

Oh finally! Thank you! It works on me! Problem solved! 🙏

**Comment by CasperH2O** [comment]
Issue concerning motherboard.json file generation has been fixed in 0.21.1.1. In the mean time, the work around is to:
- Close HC
- Delete mydocuments/handheldcompanion/cache/motherboard.json
- Open HC again

Closing ticket. 

Uninstall error is being worked on separately.
