### ISSUE TITLE
HC crashes, the calling thread cannot access this object because a different thread owns it.

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#1050]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] LENOVO
- [ ] MSI
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
AYANEO 2

**Handheld Companion Version**
0.21.0.1

**Describe the bug**
User itsnandy reported HC crashed, clear in logfile.

**To Reproduce**
Unknown

**Logs file**

```
2024-05-04 09:26:13.566 -04:00 [FTL] The calling thread cannot access this object because a different thread owns it.	   at System.Windows.Threading.Dispatcher.<VerifyAccess>g__ThrowVerifyAccess|7_0()
   at System.Windows.Media.CompositionTarget.VerifyAPIReadOnly()
   at System.Windows.Interop.HwndTarget.get_TransformToDevice()
   at System.Windows.Input.StylusLogic.GetAndCacheTransformToDeviceMatrix(PresentationSource source)
   at System.Windows.Input.StylusWisp.WispLogic.MeasureUnitsFromDeviceUnits(PresentationSource source, Point measurePoint)
   at System.Windows.Input.PenContexts.TargetPlugInCollection(RawStylusInputReport inputReport)
   at System.Windows.Input.PenContexts.InvokeStylusPluginCollection(RawStylusInputReport inputReport)
   at System.Windows.Input.StylusWisp.WispLogic.ProcessInputReport(RawStylusInputReport inputReport)
   at System.Windows.Input.PenThreadWorker.FireEvent(PenContext penContext, Int32 evt, Int32 stylusPointerId, Int32 cPackets, Int32 cbPacket, IntPtr pPackets)
   at System.Windows.Input.PenThreadWorker.ThreadProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

[HandheldCompanion-20240504.log](https://github.com/Valkirie/HandheldCompanion/files/15262531/HandheldCompanion-20240504.log)

**Comment by Valkirie** [comment]
Fixed with next EA
