### ISSUE TITLE
No virtual controller when hc starts with windows

### ISSUE THREAD

**Issue by ghostekpl** [Valkirie/HandheldCompanion#1117]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] LENOVO
- [ ] MSI
- [ ] ONEXPLAYER
- [ X] VALVE

**Device model**
Stemdeck OLED (Galileo)

**Handheld Companion Version**
0.21.4.1

**Describe the bug**
No virutal controller when HC starts along with windows. Virtual controller is also not detected by games. When I kill the HC process and start it manually the virtual controller appears and is detected by games.

**Logs file**
[HandheldCompanion-20240821.log](https://github.com/user-attachments/files/16691369/HandheldCompanion-20240821.log)

**Comment by CasperH2O** [comment]
Thansk for reporting in @ghostekpl .

This doesn't look good:

```
2024-08-21 14:14:37.981 +02:00 [FTL] Object reference not set to an instance of an object.	   at HandheldCompanion.Devices.SteamDeck.Close() in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\Devices\Valve\SteamDeck.cs:line 154
   at HandheldCompanion.Views.MainWindow.OnSystemStatusChanged(SystemStatus status, SystemStatus prevStatus) in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\Views\Windows\MainWindow.xaml.cs:line 600
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by ghostekpl** [comment]
I have the drivers installed but the oled only works with external devices or with a connected jack. When trying to reproduce this bug I did not have any audio device plugged in and I also did not have headphones plugged in

**Comment by AlIbay8** [comment]
I'm also experiencing this same issue on my GPD Win Mini 7840u (2023). I'm using Handheld Companion version 0.21.5.4. I would share my logs but I can't seem to find the logs anywhere (neither in installation folder nor Program Data).

**Comment by CasperH2O** [comment]
Logs and settings have been moved to My documents/handheld companion/logs

**Comment by AlIbay8** [comment]
Thanks, I reproduced the bug and found the log file:
[HandheldCompanion-20240824.log](https://github.com/user-attachments/files/16737020/HandheldCompanion-20240824.log)

I also tried using the GPD hardware switch to swap between mouse/keyboard and gamepad controls. When I reconnect the controller by switching it to gamepad mode, Hardware Companion recognizes and connects it as a physical controller but doesn't create the emulated controller.
