### ISSUE TITLE
Kill foreground process hotkey results in application crash

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#1125]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [x] LENOVO
- [ ] MSI
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
LNVNB161216 from LENOVO

**Handheld Companion Version**
0.21.5.4

**Describe the bug**
Reported by blooderscrew on Discord.

The application fxsound might be related as that also closes.

**Logs file**

```
2024-08-25 11:33:54.190 -06:00 [FTL] No process is associated with this object.       at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at HandheldCompanion.Commands.Functions.Windows.KillForegroundCommands.Execute(Boolean IsKeyDown, Boolean IsKeyUp) in C:\Users\caspe\source\repos\HandheldCompanion-EA\HandheldCompanion\Commands\Functions\Windows\KillForegroundCommands.cs:line 23
   at HandheldCompanion.Managers.InputsManager.CheckForSequence(Boolean IsKeyDown, Boolean IsKeyUp) in C:\Users\caspe\source\repos\HandheldCompanion-EA\HandheldCompanion\Managers\InputsManager.cs:line 114
   at HandheldCompanion.Managers.InputsManager.UpdateInputs(ControllerState controllerState) in C:\Users\caspe\source\repos\HandheldCompanion-EA\HandheldCompanion\Managers\InputsManager.cs:line 599
   at HandheldCompanion.Managers.ControllerManager.UpdateInputs(ControllerState controllerState, GamepadMotion gamepadMotion, Single deltaTimeSeconds) in C:\Users\caspe\source\repos\HandheldCompanion-EA\HandheldCompanion\Managers\ControllerManager.cs:line 1145
   at HandheldCompanion.Controllers.LegionController.UpdateInputs(Int64 ticks, Single delta, Boolean commit) in C:\Users\caspe\source\repos\HandheldCompanion-EA\HandheldCompanion\Controllers\LegionController.cs:line 334
   at HandheldCompanion.Managers.TimerManager.DoWork() in C:\Users\caspe\source\repos\HandheldCompanion-EA\HandheldCompanion\Managers\TimerManager.cs:line 34
   at PrecisionTiming.PrecisionTimer.TimerCallbackSemaphoreNoTick(Int32 hwnd, Int32 uMsg, IntPtr passThePointer, Int32 dwTime, Int32 WTF) in C:\Users\BUD\Documents\Repos\PrecisionTimer.NET\PrecisionTimer\PrecisionTimer.cs:line 119
```

[HandheldCompanion-20240825.log](https://github.com/user-attachments/files/16814371/HandheldCompanion-20240825.log)

**Comment by Valkirie** [comment]
Fixed on EA
