### ISSUE TITLE
App won't start on Ally

### ISSUE THREAD

**Issue by palamosteliaro** [Valkirie/HandheldCompanion#742]
**Device manufacturer**
- [x] ASUS

**Device model**
Rog Ally

**Handheld Companinion Version**
0.16.2.5

I have tried both new and old Bosch accelerometer drivers and older versions of HC. I am on Windows 10 and I had successfully installed and run the application on the same OS/device in the past. I wanted to try it again now with the new features, but no luck.
Running the controller service exe seems to work but the HC app won't run no matter what. Doesn't appear on task manager, no splash screen, no hourglass icon nothing. Like I never pressed enter on it.
There are .dmp files in Documents\HandheldCompanion but they are 55mb in size. If they are needed I can upload them somewhere else.

Note for the handheld companion log: The "C:\Users\benja\" path is not valid, that's not my username. I dont know where that name came from, but I don't have a "github" folder in my own document folder.

[ControllerService20230726.log](https://github.com/Valkirie/HandheldCompanion/files/12171873/ControllerService20230726.log)
[HandheldCompanion20230726.log](https://github.com/Valkirie/HandheldCompanion/files/12171874/HandheldCompanion20230726.log)

**Comment by CasperH2O** [comment]
There's a stacktrace in the hc log @Valkirie :

`2023-07-26 14:34:17.207 +03:00 [FTL] The type initializer for 'WinRT.ActivationFactory`1' threw an exception.	   at WinRT.ActivationFactory`1.As(Guid iid)
   at Windows.Devices.Sensors.Gyrometer.Make___objRef_global__Windows_Devices_Sensors_IGyrometerStatics()
   at Windows.Devices.Sensors.Gyrometer.get__objRef_global__Windows_Devices_Sensors_IGyrometerStatics()
   at Windows.Devices.Sensors.Gyrometer.GetDefault()
   at ControllerCommon.Devices.IDevice.PullSensors() in C:\Users\benja\Documents\GitHub\HandheldCompanion\ControllerCommon\Devices\IDevice.cs:line 329
   at HandheldCompanion.Views.MainWindow..ctor(FileVersionInfo _fileVersionInfo, Assembly CurrentAssembly) in C:\Users\benja\Documents\GitHub\HandheldCompanion\HandheldCompanion\Views\Windows\MainWindow.xaml.cs:line 152
   at HandheldCompanion.App.OnStartup(StartupEventArgs args) in C:\Users\benja\Documents\GitHub\HandheldCompanion\HandheldCompanion\App.xaml.cs:line 97
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at HandheldCompanion.App.Main()`

**Comment by palamosteliaro** [comment]
I saw on Discord others saying they had to enable UAC to get the App started, but it didn't help with me. Enabling UAC shows the dialog, but when I press Yes, nothing happens.

**Comment by palamosteliaro** [comment]
> There's a stacktrace in the hc log @Valkirie :

I don't really understand that, anything I could try to solve this?

**Comment by CasperH2O** [comment]
@palamosteliaro there is no need for you to do anything. The stack trace needs to be analyzed and a fix needs to be implemented for this case.

**Comment by CasperH2O** [comment]
@palamosteliaro can you confirm this is still a problem with release 0.18, the latest public? It seems quite unique to your device as plenty of people can install HC on ROG Ally just fine.

**Comment by palamosteliaro** [comment]
> @palamosteliaro can you confirm this is still a problem with release 0.18, the latest public? It seems quite unique to your device as plenty of people can install HC on ROG Ally just fine.

I don't have the Ally, I switched it with a Legion Go. Interestingly, it also doesn't start on the Go, exact same behavior. I am guessing its something to do by using LTSC version of W10? I have seen reports of it working on W10 from users. Any Idea what's necessary to run the app, that's missing from LTSC? Thanks!

**Comment by CasperH2O** [comment]
So, @palamosteliaro it seems it works for you and since you no longer have the device, it can't be reproduced?
