### ISSUE TITLE
ControllerManager.cs - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#868]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE
- [x] LENOVO

**Device model**
Legion Go

**Handheld Companinion Version**
0.19.1.3

**Describe the bug**
HC crashes on start or on hotkey usage.

Log shows this:

```
2023-12-10 05:30:46.377 -05:00 [DBG] Settings HIDInstancePath set to 
2023-12-10 05:30:46.377 -05:00 [DBG] XInput controller Legion Controller for Windows  unplugged
2023-12-10 05:30:46.380 -05:00 [FTL] Object reference not set to an instance of an object.       at HandheldCompanion.Managers.ControllerManager.SetTargetController(String baseContainerDeviceInstanceId, Boolean IsPowerCycling) in C:\Users\NUC\Documents\GitHub\HandheldCompanion-EA\HandheldCompanion\Managers\ControllerManager.cs:line 890
   at HandheldCompanion.Managers.ControllerManager.XUsbDeviceArrived(PnPDetails details, DeviceEventArgs obj) in C:\Users\NUC\Documents\GitHub\HandheldCompanion-EA\HandheldCompanion\Managers\ControllerManager.cs:line 798
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2023-12-10 05:31:34.549 -05:00 [INF] HandheldCompanion, Version=0.19.1.3, Culture=neutral, PublicKeyToken=null (0.19.1.3)
```

**To Reproduce**
1. Inconsistent on HC start

**Logs file**

[HandheldCompanion-20231210.log](https://github.com/Valkirie/HandheldCompanion/files/13627494/HandheldCompanion-20231210.log)

**Comment by Valkirie** [comment]
Looks like a ClearTargetController() call was made while SetTargetController() is running. We can either:
- lazy: use try catch
- proper: use a lock so clear waits for set to be completed

**Comment by Valkirie** [comment]
Used option two on EA
