### ISSUE TITLE
TaskManager.cs results in HC crash shortly after starting

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#896]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE
- [x] LENOVO

**Device model**
Legion Go

**Handheld Companinion Version**
0.19.1.8

**Describe the bug**
HC crashes on start after a few seconds.

**Logs file**

```
2023-12-19 13:06:51.922 -08:00 [FTL] An internal error occurred. (0x8007054F)	   at Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.GetTasks(Int32 flags)
   at Microsoft.Win32.TaskScheduler.TaskFolder.GetTasks(Regex filter)
   at Microsoft.Win32.TaskScheduler.TaskService.FindTaskInFolder(TaskFolder fld, Regex taskName, List`1& results, Boolean recurse)
   at Microsoft.Win32.TaskScheduler.TaskService.FindTaskInFolder(TaskFolder fld, Regex taskName, List`1& results, Boolean recurse)
   at Microsoft.Win32.TaskScheduler.TaskService.FindTaskInFolder(TaskFolder fld, Regex taskName, List`1& results, Boolean recurse)
   at Microsoft.Win32.TaskScheduler.TaskService.FindTaskInFolder(TaskFolder fld, Regex taskName, List`1& results, Boolean recurse)
   at Microsoft.Win32.TaskScheduler.TaskService.FindAllTasks(Regex name, Boolean searchAllFolders)
   at Microsoft.Win32.TaskScheduler.TaskService.FindTask(String name, Boolean searchAllFolders)
   at HandheldCompanion.Managers.TaskManager.Start() in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\Managers\TaskManager.cs:line 38
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

[HandheldCompanion-20231219.log.txt](https://github.com/Valkirie/HandheldCompanion/files/13723784/HandheldCompanion-20231219.log.txt)

**Comment by Valkirie** [comment]
Fixed on EA

**Comment by CasperH2O** [comment]
Fixed, released.
