### ISSUE TITLE
PenThreadWorker. The calling thread cannot access this object because a different thread owns it.

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/HandheldCompanion#934]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE
- [x] LENOVO

**Device model**
Legion Go

**Handheld Companinion Version**
0.20.2.7

**Describe the bug**
HC crashes, seems related to touch screen input.

```
2024-01-08 22:20:45.632 -05:00 [FTL] The calling thread cannot access this object because a different thread owns it.       at System.Windows.Threading.Dispatcher.<VerifyAccess>g__ThrowVerifyAccess|7_0()
   at System.Windows.Media.CompositionTarget.VerifyAPIReadOnly()
   at System.Windows.Interop.HwndTarget.get_TransformToDevice()
   at System.Windows.Input.PenContexts.TargetPlugInCollection(RawStylusInputReport inputReport)
   at System.Windows.Input.PenContexts.InvokeStylusPluginCollection(RawStylusInputReport inputReport)
   at System.Windows.Input.StylusWisp.WispLogic.ProcessInputReport(RawStylusInputReport inputReport)
   at System.Windows.Input.PenThreadWorker.FireEvent(PenContext penContext, Int32 evt, Int32 stylusPointerId, Int32 cPackets, Int32 cbPacket, IntPtr pPackets)
   at System.Windows.Input.PenThreadWorker.ThreadProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Logs file**

[HandheldCompanion-20240108.txt](https://github.com/Valkirie/HandheldCompanion/files/13869387/HandheldCompanion-20240108.txt)

**Comment by Valkirie** [comment]
Seams to be related to: https://github.com/dotnet/wpf/issues/6829

**Comment by CasperH2O** [comment]
Has been fixed by using a fork of WPF with newer features and bugfixes. Leaving this open for now until we can use the formal WPF library again.

**Comment by Valkirie** [comment]
Should be fixed already.

**Comment by CasperH2O** [comment]
This has been fixed with WPF fork we are now using. I have subscribed to the original ticket so that we can remove the workaround once it has been fixed my Microsoft (if ever).

**Comment by CasperH2O** [comment]
User reported having this issue with 0.20.5.4, right after waking from hibernate (or sleep?) on a Legion Go.

Error:

```
2024-04-03 14:08:19.567 +02:00 [FTL] The calling thread cannot access this object because a different thread owns it.	   at System.Windows.Threading.Dispatcher.<VerifyAccess>g__ThrowVerifyAccess|7_0()
   at System.Windows.Media.CompositionTarget.VerifyAPIReadOnly()
   at System.Windows.Interop.HwndTarget.get_TransformToDevice()
   at System.Windows.Input.PenContexts.TargetPlugInCollection(RawStylusInputReport inputReport)
   at System.Windows.Input.PenContexts.InvokeStylusPluginCollection(RawStylusInputReport inputReport)
   at System.Windows.Input.StylusWisp.WispLogic.ProcessInputReport(RawStylusInputReport inputReport)
   at System.Windows.Input.PenThreadWorker.FireEvent(PenContext penContext, Int32 evt, Int32 stylusPointerId, Int32 cPackets, Int32 cbPacket, IntPtr pPackets)
   at System.Windows.Input.PenThreadWorker.ThreadProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
```

Log:

[HandheldCompanion-20240403.log](https://github.com/Valkirie/HandheldCompanion/files/14852661/HandheldCompanion-20240403.log)
