### ISSUE TITLE
Crash when dismissing quick settings window

### ISSUE THREAD

**Issue by indiesaudi** [Valkirie/HandheldCompanion#950]
**Device manufacturer**
- [x] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
Ayaneo Air 1S

**Handheld Companinion Version**
0.20.3.0

**Describe the bug**
Crash when dismissing quick settings window. 

**To Reproduce**
1. Press the quick settngs shortcut, 
2. Press the quick settings shortcut again ti dismiss it. 

**Expected behavior**
Dismisses quick settings window

**Logs file**

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexMustBeLessException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at HandheldCompanion.Managers.LayoutManager.MapController(ControllerState controllerState) in C:\Users\hamed\OneDrive\GitHub\HandheldCompanion\HandheldCompanion\Managers\LayoutManager.cs:line 380
   at HandheldCompanion.Managers.ControllerManager.UpdateInputs(ControllerState controllerState) in C:\Users\hamed\OneDrive\GitHub\HandheldCompanion\HandheldCompanion\Managers\ControllerManager.cs:line 1091
   at HandheldCompanion.Controllers.IController.UpdateInputs(Int64 ticks) in C:\Users\hamed\OneDrive\GitHub\HandheldCompanion\HandheldCompanion\Controllers\IController.xaml.cs:line 151
   at HandheldCompanion.Controllers.XInputController.UpdateInputs(Int64 ticks, Boolean commit) in C:\Users\hamed\OneDrive\GitHub\HandheldCompanion\HandheldCompanion\Controllers\XInputController.cs:line 124
   at HandheldCompanion.Controllers.XInputController.<Plug>b__9_0(Int64 ticks) in C:\Users\hamed\OneDrive\GitHub\HandheldCompanion\HandheldCompanion\Controllers\XInputController.cs:line 152
   at HandheldCompanion.Managers.TimerManager.DoWork() in C:\Users\hamed\OneDrive\GitHub\HandheldCompanion\HandheldCompanion\Managers\TimerManager.cs:line 30
   at PrecisionTiming.PrecisionTimer.TimerCallbackNoTick(Int32 hwnd, Int32 uMsg, IntPtr passThePointer, Int32 dwTime, Int32 
```

**Comment by MSeys** [comment]
As call stack mentions, this is a crash more related to your current layout rather than Quick Tools itself. Something in your layout is causing a crash.

**Comment by indiesaudi** [comment]
WOndering what kind of layout would cause this? I added 4 buttons to the layout and that is about it.

Changing line 378 to the below seems to solve the problem.
if (idx+1 < sortedActions.Count ) 

Which files in settings do I need to check and share here to get to the bottom of it.

**Comment by CasperH2O** [comment]
@indiesaudi glad to hear you tested a fix. Do you want to do a PR or do you prefer someone else picks it up?

**Comment by indiesaudi** [comment]
I didn't come up with a solution, feels like I am taking the credit if I submitted the PR myself.

**Comment by CasperH2O** [comment]
Your call @MSeys . ;-)

**Comment by MSeys** [comment]
To me, it doesn't matter who does it, as long as it gets fixed.

**Comment by indiesaudi** [comment]
https://github.com/Valkirie/HandheldCompanion/pull/951

**Comment by CasperH2O** [comment]
Fixed, thank you @indiesaudi @MSeys
