### ISSUE TITLE
Unhandled Null Reference Exception in DynamicLightingManager.InitializeDirect3DDevice()

### ISSUE THREAD

**Issue by breakwinz** [Valkirie/HandheldCompanion#958]
**Device manufacturer**
- [x] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
Geek 1S

**Handheld Companinion Version**
0.20.3.0

**Describe the bug**
Null reference exception, unhandled causing HC to crash. 
 HandheldCompanion.Managers.DynamicLightingManager.InitializeDirect3DDevice() 

**To Reproduce**
Not sure how this is happening but definitely happens when i have games open. Seems sporadic though and havent found a pattern

**Expected behavior**
Handle the exception by adding a catch. Given the non critical class this is in "DynamicLightingManager", I feel we can turn off DymanicLightingManager and simply raise a notification to the user something went wrong.

**Screenshots**
N/A

**Logs file**
[hc crash.zip](https://github.com/Valkirie/HandheldCompanion/files/13994314/hc.crash.zip)
Added a zip file containing a evtx file. Can be opened in Event Viewer in windows

**Comment by breakwinz** [comment]
Application: HandheldCompanion.exe
CoreCLR Version: 8.0.123.58001
.NET Version: 8.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at HandheldCompanion.Managers.DynamicLightingManager.InitializeDirect3DDevice() in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\Managers\DynamicLightingManager.cs:line 124
   at HandheldCompanion.Managers.DynamicLightingManager.InitializeDirect3DDevice() in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\Managers\DynamicLightingManager.cs:line 129
   at HandheldCompanion.Managers.DynamicLightingManager.SystemManager_DisplaySettingsChanged(ScreenResolution resolution) in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\Managers\DynamicLightingManager.cs:line 95
   at HandheldCompanion.Managers.SystemManager.SystemEvents_DisplaySettingsChanged(Object sender, EventArgs e) in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\Managers\SystemManager.cs:line 347
   at InvokeStub_EventHandler.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Microsoft.Win32.SystemEvents.SystemEventInvokeInfo.InvokeCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at HandheldCompanion.App.Main()

**Comment by MSeys** [comment]
That is not the same as Ambilight, no. Exception isn't related to it.
https://github.com/Valkirie/HandheldCompanion/blob/main/HandheldCompanion%2FManagers%2FDynamicLightingManager.cs#L124

There's a possibility device is null here. If device started as null, and the creation fails, then device would be null in the catch. 

Would have to be investigated.

**Comment by CasperH2O** [comment]
Fixed for next release. Valkirie/HandheldCompanion-EA#176
