### ISSUE TITLE
Crash on launch with Intel GPUs

### ISSUE THREAD

**Issue by romracer** [Valkirie/HandheldCompanion#981]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [ ] GPD
- [ x] ONEXPLAYER
- [ ] VALVE

**Device model**
Onexplayer mini Intel

**Handheld Companinion Version**
0.20.4.1

**Describe the bug**
crash on launch

**To Reproduce**
1. Try to run HC

**Expected behavior**
It would run.

**Logs file**
```
Application: HandheldCompanion.exe
CoreCLR Version: 8.0.123.58001
.NET Version: 8.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'HandheldCompanion.Managers.GPUManager' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'IGCL_Wrapper.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at HandheldCompanion.IGCL.IGCLBackend.IntializeIgcl()
   at HandheldCompanion.IGCL.IGCLBackend.Initialize() in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\IGCL\IGCLBackend.cs:line 446
   at HandheldCompanion.GraphicsProcessingUnit.IntelGPU..ctor() in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\GraphicsProcessingUnit\IntelGPU.cs:line 133
   at HandheldCompanion.GraphicsProcessingUnit.GPU.GetCurrent() in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\GraphicsProcessingUnit\GPU.cs:line 88
   at HandheldCompanion.Managers.GPUManager..cctor() in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\Managers\GPUManager.cs:line 20
   --- End of inner exception stack trace ---
   at HandheldCompanion.Managers.GPUManager.add_Initialized(InitializedEventHandler value)
   at HandheldCompanion.Views.QuickPages.QuickProfilesPage..ctor() in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\Views\QuickPages\QuickProfilesPage.xaml.cs:line 57
   at HandheldCompanion.Views.QuickPages.QuickProfilesPage..ctor(String Tag) in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\Views\QuickPages\QuickProfilesPage.xaml.cs:line 38
   at HandheldCompanion.Views.Windows.OverlayQuickTools..ctor() in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\Views\Windows\OverlayQuickTools.xaml.cs:line 111
   at HandheldCompanion.Views.MainWindow.loadWindows() in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\Views\Windows\MainWindow.xaml.cs:line 453
   at HandheldCompanion.Views.MainWindow..ctor(FileVersionInfo _fileVersionInfo, Assembly CurrentAssembly) in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\Views\Windows\MainWindow.xaml.cs:line 224
   at HandheldCompanion.App.OnStartup(StartupEventArgs args) in D:\a\HandheldCompanion\HandheldCompanion\HandheldCompanion\App.xaml.cs:line 100
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at HandheldCompanion.App.Main()

```

I see the IGCL_Wrapper.dll in the HC directory.  It must be missing a dependency.

**Comment by MSeys** [comment]
@Valkirie

**Comment by romracer** [comment]
Dependency walker seems like the wrapper wants MSVCP140D.DLL (the debug library) which is not part of MSVC++ redistributables.

**Comment by CasperH2O** [comment]
@romracer thanks for reporting and checking some things alrady. Do you have an external GPU connected by any chance?

**Comment by romracer** [comment]
Nope.  Connected to the Onexplayer dock but that's just video out.  This is an Intel GPU device though.  0.20.4.1 works fine on my AMD device (AOKZOE A1).

Looks like that wrapper was compiled in debug mode instead of release mode.  Dependency walker shows it linked to all sorts of *D.DLL libraries.

**Comment by Valkirie** [comment]
Thanks for the report, will look into it.

**Comment by romracer** [comment]
Perhaps need `--config Release` on the cmake command for the wrapper library?  If you compile one of those and attach it, I can replace the wrapper DLL on this device and see if HC starts up.

**Comment by Valkirie** [comment]
Try this one.
[IGCL_Wrapper.zip](https://github.com/Valkirie/HandheldCompanion/files/14152700/IGCL_Wrapper.zip)

**Comment by romracer** [comment]
Replacing with that file works.

**Comment by Valkirie** [comment]
Should be fixed with EA
